#!/usr/bin/env ruby

# script/scrape: Scrape http://www.buienalarm.nl/ for projected precipitation
#
# Usage: script/scrape <location>
#
# Example: script/scrape rotterdam

require_relative "../lib/buienalarm"

location = ARGV.shift or abort "Usage: script/scrape <location>"

puts "===> Scraping Buienalarm.nl...\n\n"

begin
  result = Buienalarm::Scraper.scrape(location)
  puts "Projected rainfall for the next two hours in #{location}:\n\n"
  result.each do |entry|
    puts "#{entry[:time].strftime("%H:%M")} - %.2fmm/hour (#{entry[:level]})" % entry[:precip]
  end
rescue Exception => e
  puts e
end

# vim: set ft=ruby:
