#!/bin/sh

# script/test: Run the test suite. Optionally pass in a path to an
#              individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

echo "===> Running tests..."

if [ -n "$1" ]; then
  # Pass arguments to test call to run a single test.
  ruby -Ilib:test "$1"
else
  ruby -Ilib:test test/test_*.rb
fi
